data <- read.csv('household_power_consumption.txt', header = TRUE, sep = ';', na.strings = '?')
data2 <- transform(data, Date = as.Date(Date, "%d/%m/%Y"))
data2$DateTime <- as.POSIXct(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
data3 <- subset(data2, Date == "2007-02-01" | Date == "2007-02-02")
par(mfcol = c(1,1), mar = c(5,5,2,2))
with(data3, hist(Global_active_power, col = "red", xlab = 'Global Active Power (kilowatts)', main = 'Global Active power'))
png(file = 'plot1.png')
par(mfcol = c(1,1), mar = c(5,5,2,2))
with(data3, hist(Global_active_power, col = "red", xlab = 'Global Active Power (kilowatts)', main = 'Global Active power'))
dev.off()