data <- read.csv('household_power_consumption.txt', header = TRUE, sep = ';', na.strings = '?')
data2 <- transform(data, Date = as.Date(Date, "%d/%m/%Y"))
data2$DateTime <- as.POSIXct(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
data3 <- subset(data2, Date == "2007-02-01" | Date == "2007-02-02")
par(mfcol = c(2,2), mar = c(5,4,1,2))
with(data3, plot(DateTime,Global_active_power, type = 'l',  ylab = 'Global Active Power', xlab = ''))
with(data3, plot(DateTime, Sub_metering_1, type = 'l', xlab = '', ylab = 'Energy sub metering'))
with(data3, lines(DateTime, Sub_metering_2, col = 'red'))
with(data3, lines(DateTime, Sub_metering_3, col = 'blue'))
legend('topright', pch = '', lwd = 1, col = c('black', 'red', 'blue'), legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'), bty = "n")
with(data3,plot(DateTime, Voltage, type = 'l'))
with(data3,plot(DateTime, Global_reactive_power, type = 'l'))
png(file = "plot4.png")
par(mfcol = c(2,2), mar = c(5,4,1,2))
with(data3, plot(DateTime,Global_active_power, type = 'l',  ylab = 'Global Active Power', xlab = ''))
with(data3, plot(DateTime, Sub_metering_1, type = 'l', xlab = '', ylab = 'Energy sub metering'))
with(data3, lines(DateTime, Sub_metering_2, col = 'red'))
with(data3, lines(DateTime, Sub_metering_3, col = 'blue'))
legend('topright', pch = '', lwd = 1, col = c('black', 'red', 'blue'), legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'), bty = "n")
with(data3,plot(DateTime, Voltage, type = 'l'))
with(data3,plot(DateTime, Global_reactive_power, type = 'l'))
dev.off()