data <- read.csv('household_power_consumption.txt', header = TRUE, sep = ';', na.strings = '?')
data2 <- transform(data, Date = as.Date(Date, "%d/%m/%Y"))
data2$DateTime <- as.POSIXct(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
data3 <- subset(data2, Date == "2007-02-01" | Date == "2007-02-02")
par(mfcol = c(1,1), mar = c(5,5,2,2))
with(data3, plot(DateTime, Sub_metering_1, type = 'l', xlab = '', ylab = 'Energy sub metering'))
with(data3, lines(DateTime, Sub_metering_2, col = 'red'))
with(data3, lines(DateTime, Sub_metering_3, col = 'blue'))
legend('topright', pch = '', lwd = 1, col = c('black', 'red', 'blue'), legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'))
png(file = "plot3.png")
par(mfcol = c(1,1), mar = c(5,5,2,2))
with(data3, plot(DateTime, Sub_metering_1, type = 'l', xlab = '', ylab = 'Energy sub metering'))
with(data3, lines(DateTime, Sub_metering_2, col = 'red'))
with(data3, lines(DateTime, Sub_metering_3, col = 'blue'))
legend('topright', pch = '', lwd = 1, col = c('black', 'red', 'blue'), legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'))
dev.off()